name: Public API Tests

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    timeout-minutes: 30
    runs-on: blacksmith-16vcpu-ubuntu-2404
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build && echo 'done'

      # - name: Run tests
      #   working-directory: apps/web
      #   env:
      #     E2E_BASE_URL: ${{ github.event.deployment_status.environment_url }}
      #     E2E_TOKEN: ${{ secrets.E2E_TOKEN }}
      #     E2E_TOKEN_OLD: ${{ secrets.E2E_TOKEN_OLD }}
      #     E2E_PUBLISHABLE_KEY: ${{ secrets.E2E_PUBLISHABLE_KEY }}
      #     QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
      #     QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
      #     NEXT_PUBLIC_NGROK_URL: ${{ github.event.deployment_status.environment_url }}
      #   run: pnpm test
